### ISSUE TITLE
HttpLinkServerException

### ISSUE THREAD

**Issue by manuelduarte077** [baconcheese113/graphql-flutter-artemis-example#1]
Hello, I was seeing your conversation with the creator of graphql_codegen, then I came to review the example that I created using the package, and I get this error

![Screen Shot 2022-07-25 at 09 45 27](https://user-images.githubusercontent.com/46093689/180828500-bffae970-39fc-414b-8808-b505b3ddd245.png)

**Comment by baconcheese113** [comment]
Are you using this repo? `graphql-flutter-artemis-example`?

**Comment by manuelduarte077** [comment]
I got the wrong repository

https://github.com/baconcheese113/graphql_codegen_example I am using this
